[package]
name = "blobsey-wasm"
path = "src/main.rs"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4"

[dependencies.web-sys]
version = "0.3"
features = [
    "console",
    "Document"
]